name: Jenkins Job Builder
description: Update Jenkins Jobs
branding:
  icon: message-circle
  color: green

inputs:
  jjb_user:
    description: Jenkins user account name
    required: true
  jjb_password:
    description: Jenkins API token (https://www.jenkins.io/blog/2018/07/02/new-api-token-system/, preferred), or password
    required: true
  jjb_dir:
    description: Path to directory with JJB YAML files, searched recursively
    required: false
    default: jobs
  jjb_ini:
    description: Path to jenkins_jobs.ini file. Specify URL here. https://jenkins-job-builder.readthedocs.io/en/latest/execution.html
    required: false
    default: jenkins_jobs.ini
  jenkins_cert:
    description: Path to Jenkins web server certificate file. Set if you use self-signed cert in Jenkins.
    required: false
    default: "false"
  delete_old:
    description: Delete obsolete jobs (--delete-old flag)
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - run: |
        set -xeu -o pipefail
        pip3 install -r "$GITHUB_ACTION_PATH/requirements.txt"
        $GITHUB_ACTION_PATH/action.sh
      shell: bash
      env:
        INPUT_JJB_USER: ${{ inputs.jjb_user }}
        INPUT_JJB_PASSWORD: ${{ inputs.jjb_password }}
        INPUT_JOBS_DIR: ${{ inputs.jjb_dir }}
        INPUT_INI_FILE: ${{ inputs.jjb_ini }}
        INPUT_JENKINS_CERT: ${{ inputs.jenkins_cert }}
        INPUT_DELETE_OLD: ${{ inputs.delete_old }}
